import {useEffect,useMemo,useRef,useState} from 'react'
import {useRegisterSW} from 'virtual:pwa-register/react'
import Map from './Map'
import Icon,{categoryIcon} from './Icon'
import {REGIONS,CATEGORIES,openingStatus,filterPlaces,budgetLabel,mapsUrl,safeRead,safeWrite,distance} from './model'
const base=import.meta.env.BASE_URL
function Dialog({children,onClose,label}) {
 const ref=useRef(null)
 useEffect(()=>{ref.current.showModal();return()=>ref.current?.close()},[])
 return <dialog ref={ref} className="sheet" aria-label={label} onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose()}}><div className="sheet-body"><button className="close-button" aria-label="關閉" onClick={onClose}><Icon name="close"/></button>{children}</div></dialog>
}
function Photo({place,large=false}) {
 const [failed,setFailed]=useState(false)
 return place.photo?.url&&!failed?<figure className={large?'place-photo large':'place-photo'}><img src={base+place.photo.url} alt={place.photo.alt} onError={()=>setFailed(true)}/>{large&&<figcaption>{place.photo.kind==='landmark'?'景點實景':'到場辨認'} · <a href={place.photo.sourceUrl} target="_blank" rel="noreferrer">{place.photo.credit}</a> · <a href={place.photo.licenseUrl} target="_blank" rel="noreferrer">{place.photo.license}</a> · 已縮圖</figcaption>}</figure>:<div className={large?'photo-pending large':'photo-pending'}><Icon name={place.kind==='attraction'?'landmark':categoryIcon(place.category)} size={large?42:26}/>{large&&<span>{place.kind==='attraction'?'實景照片待核實':'門面照片待核實'}<br/><small>請按地址及招牌辨認，不以食物照代替</small></span>}</div>
}
function PlaceCard({p,favorite,onFavorite,onSelect,now,location}) {
 const status=openingStatus(p,now)
 return <article className="place-card"><button className="card-main" onClick={onSelect}><Photo place={p}/><div className="card-copy"><span className="eyebrow">{p.district} · {p.category}</span><h3>{p.name}</h3><p>{p.signature}</p><div className="card-meta"><b>{budgetLabel(p)}</b><span className={'status '+status.state}>{status.label}</span>{location&&<span>{distance(location,p).toFixed(1)} km</span>}</div></div></button><button className={'favorite-button '+(favorite?'is-saved':'')} aria-label={(favorite?'取消收藏':'收藏')+p.name} aria-pressed={favorite} onClick={onFavorite}><Icon name={favorite?'saved':'heart'}/></button>{p.michelin&&<span className="michelin-label">M · {p.michelin}</span>}</article>
}
export default function App(){
 const [places,setPlaces]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const [view,setView]=useState('map'),[mode,setMode]=useState('all'),[region,setRegion]=useState('全香港'),[category,setCategory]=useState('全部'),[query,setQuery]=useState('')
 const [open,setOpen]=useState(false),[budget,setBudget]=useState(0),[nearby,setNearby]=useState(false),[showFilters,setShowFilters]=useState(false),[install,setInstall]=useState(false),[about,setAbout]=useState(false)
 const [favorites,setFavorites]=useState(()=>safeRead('favorites')),[visited,setVisited]=useState(()=>safeRead('visited')),[route,setRoute]=useState(()=>safeRead('route'))
 const [selected,setSelected]=useState(null),[location,setLocation]=useState(null),[now,setNow]=useState(new Date()),[busy,setBusy]=useState(false)
 const {needRefresh:[needRefresh,setNeedRefresh],updateServiceWorker}=useRegisterSW()
 const load=async(fresh=false)=>{setError('');try{const res=await fetch(base+'places.json'+(fresh?'?v='+Date.now():''),fresh?{cache:'no-store'}:{});if(!res.ok)throw Error();const data=await res.json();if(!Array.isArray(data)||!data.length||data.some(p=>!p.id||!Number.isFinite(p.lat)||!Number.isFinite(p.lng)))throw Error();setPlaces(data);return true}catch{setError('地點資料暫時無法載入。請連線後重試；收藏仍然保留。');return false}finally{setLoading(false)}}
 useEffect(()=>{load();const timer=setInterval(()=>setNow(new Date()),60000);return()=>clearInterval(timer)},[])
 useEffect(()=>{if(!places.length)return;const read=()=>{const id=new URLSearchParams(locationHash()).get('place');setSelected(places.find(p=>p.id===id)||null)};read();window.addEventListener('hashchange',read);window.addEventListener('popstate',read);return()=>{window.removeEventListener('hashchange',read);window.removeEventListener('popstate',read)}},[places])
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),5500);return()=>clearTimeout(t)},[notice])
 function locationHash(){return window.location.hash.slice(1)}
 const select=p=>{setSelected(p);history.replaceState(null,'',window.location.pathname+(p?'#place='+encodeURIComponent(p.id):''))}
 const toggle=(key,values,setter,id)=>{const next=values.includes(id)?values.filter(x=>x!==id):[...values,id];setter(next);if(!safeWrite(key,next))setNotice('瀏覽器未能儲存，這次變更只會保留至關閉頁面。')}
 const locate=()=>{if(!navigator.geolocation){setNotice('此瀏覽器不支援定位。');return}setNotice('正在取得位置…');navigator.geolocation.getCurrentPosition(({coords})=>{setLocation({lat:coords.latitude,lng:coords.longitude});setNotice('已按你的位置排列地點。')},()=>{setNearby(false);setNotice('未能取得位置。請允許定位，或直接按地區探索。')},{enableHighAccuracy:true,timeout:12000,maximumAge:30000})}
 const filtered=useMemo(()=>filterPlaces(places,{mode,region,category,query,open,budget,nearby,saved:view==='favorites'},favorites,location,now),[places,mode,region,category,query,open,budget,nearby,view,favorites,location,now])
 const visibleCategories=CATEGORIES.filter(c=>c==='全部'||places.some(p=>p.category===c))
 const switchMode=m=>{setMode(m);setCategory('全部');select(null)}
 const switchView=v=>{setView(v);select(null)}
 const clear=()=>{setQuery('');setCategory('全部');setMode('all');setRegion('全香港');setOpen(false);setBudget(0);setNearby(false)}
 const addRoute=p=>{if(route.includes(p.id)){setNotice('這個地點已在口袋行程。');return}const next=[...route,p.id];setRoute(next);safeWrite('route',next);setNotice('已加入口袋行程，可自行調整先後次序。')}
 const changeRoute=next=>{setRoute(next);safeWrite('route',next)}
 const update=async()=>{setBusy(true);const refreshed=await load(true);try{const reg=await navigator.serviceWorker?.getRegistration(base);await Promise.race([reg?.update(),new Promise((_,reject)=>setTimeout(reject,12000))]);if(reg?.waiting)setNeedRefresh(true);setNotice(refreshed?'已檢查已發佈資料；不會清除收藏。':'資料更新未成功；現有地點及收藏已保留。')}catch{setNotice('App 更新檢查未成功，請稍後重試。')}finally{setBusy(false)}}
 const share=async p=>{try{const url=window.location.origin+window.location.pathname+'#place='+encodeURIComponent(p.id);if(navigator.share)await navigator.share({title:p.name,text:p.signature,url});else{await navigator.clipboard.writeText(url);setNotice('地點連結已複製。')}}catch(e){if(e.name!=='AbortError')setNotice('未能分享，請複製網址列的地點連結。')}}
 const detailStatus=selected&&openingStatus(selected,now)
 const explore=['map','list','favorites'].includes(view)
 return <main className="app">
  <aside className="sidebar">
   <header className="masthead"><a className="wordmark" href={base} aria-label="香港街角首頁"><span className="brand-mark">港</span><span>香港街角<small>HONG KONG / ON FOOT</small></span></a><button className="icon-button install" aria-label="加入主畫面" onClick={()=>setInstall(true)}><Icon name="plus"/></button></header>
   <div className="intro"><span className="edition">城市散步手帖 <i>VOL. 01</i></span><h1>食一餐。<br/><em>行一段。</em></h1><p>轉個街角，遇見另一個香港。</p><div className="route-line" aria-hidden="true"><i/><span/><i/><span/><i/></div></div>
   {explore&&<section className="explore-controls" aria-label="探索篩選">
    <label className="search"><Icon name="search"/><input aria-label="搜尋地點" placeholder="店名、名物、街道或地區" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="清除搜尋" onClick={()=>setQuery('')}><Icon name="close" size={18}/></button>}</label>
    <div className="area-row"><span className="label">今次行邊區？</span><select aria-label="探索地區" value={region} onChange={e=>setRegion(e.target.value)}>{REGIONS.map(r=><option key={r}>{r}</option>)}</select></div>
    <div className="modes" aria-label="地點類型">{[['all','全部街角'],['restaurant','食嘢'],['attraction','行吓']].map(([m,t])=><button key={m} className={mode===m?'active':''} aria-pressed={mode===m} onClick={()=>switchMode(m)}>{t}</button>)}</div>
    {mode!=='attraction'&&<div className="cuisine-strip" aria-label="按菜式分類">{visibleCategories.map(c=><button key={c} className={category===c?'active':''} aria-pressed={category===c} onClick={()=>{setCategory(c);if(c!=='全部')setMode('restaurant')}}>{c}</button>)}</div>}
    <div className="quick-filters"><button className={open?'active':''} aria-pressed={open} onClick={()=>setOpen(!open)}><span className="live-dot"/>現在營業</button><button className={budget||nearby?'active':''} onClick={()=>setShowFilters(true)}><Icon name="filter" size={17}/>距離／預算{budget||nearby?' · 已篩選':''}</button></div>
   </section>}
   {!explore&&<div className="section-intro"><span className="eyebrow">A LITTLE WANDER</span><h2>你的口袋行程</h2><p>從地點卡加入，自訂步行的節奏。</p></div>}
   <div className="sidebar-foot"><button aria-label="收錄準則與資料來源" onClick={()=>setAbout(true)}><span className="about-icon">i</span>收錄準則與資料來源 ↗</button><button className="update-button" aria-label="檢查更新" onClick={update} disabled={busy}><Icon name="refresh" size={16}/>{busy?'檢查中…':'檢查更新'}</button></div>
  </aside>
  <section className={'main-content '+view}>
   <div className="desktop-context"><span>HONG KONG / 香港</span><span>22°17′ N · 114°10′ E</span><button onClick={()=>setAbout(true)}>關於這份地圖 ↗</button></div>
   {error&&<div className="load-error" role="alert">{error}<button onClick={()=>load(true)}>重試</button></div>}
   {loading?<div className="empty"><span className="brand-mark">港</span><h2>正在打開城市手帖…</h2></div>:view==='map'?<Map places={filtered} selected={selected} onSelect={select} location={location} region={region} now={now} onLocate={locate}/>:view==='route'?<div className="page-scroll"><div className="page-title"><span className="eyebrow">MY WALK</span><h2>留一點時間，慢慢行。</h2><p>順序由你決定；不代表已訂位，亦不是步行時間估算。</p></div>{route.length?route.map((id,i)=>{const p=places.find(p=>p.id===id);if(!p)return null;return <article className="route-stop" key={id}><span className="stop-number">{String(i+1).padStart(2,'0')}</span><div><button className="text-button" onClick={()=>select(p)}><h3>{p.name}</h3></button><p>{p.district} · {p.signature}</p><div className="route-actions"><button disabled={i===0} onClick={()=>{const n=[...route];[n[i-1],n[i]]=[n[i],n[i-1]];changeRoute(n)}} aria-label={'向上移動'+p.name}>↑</button><button disabled={i===route.length-1} onClick={()=>{const n=[...route];[n[i+1],n[i]]=[n[i],n[i+1]];changeRoute(n)}} aria-label={'向下移動'+p.name}>↓</button><a href={mapsUrl(p)} target="_blank" rel="noreferrer">導航 ↗</a><button onClick={()=>changeRoute(route.filter(x=>x!==id))}>移除</button></div></div></article>}):<div className="empty"><Icon name="route" size={44}/><h3>先揀一個想去的街角。</h3><p>點開餐廳或景點，按「加入行程」。</p><button className="primary" onClick={()=>switchView('map')}>打開地圖</button></div>}</div>:<div className="page-scroll"><div className="page-title"><span className="eyebrow">{view==='favorites'?'SAVED FOR LATER':'YOUR NEIGHBOURHOOD NOTES'}</span><h2>{view==='favorites'?'想去的，都留低。':'下一站，'+(region==='全香港'?'隨心行。':region+'。')}</h2><p>{filtered.length} 個地點{location?' · 按直線距離排序':''}</p></div><div className="cards">{filtered.map(p=><PlaceCard key={p.id} p={p} now={now} location={location} favorite={favorites.includes(p.id)} onFavorite={()=>toggle('favorites',favorites,setFavorites,p.id)} onSelect={()=>select(p)}/>)}</div>{!filtered.length&&<div className="empty"><Icon name="search" size={40}/><h3>{view==='favorites'&&!favorites.length?'還未收藏街角。':'這組條件暫時沒有結果。'}</h3><p>收錄仍在擴充；沒有結果不代表區內沒有好店。</p><button onClick={clear}>清除篩選</button></div>}</div>}
   {view==='map'&&!loading&&<div className="map-legend"><span><i className="legend-pin"/>餐廳</span><span><i className="legend-square"/>景點實景</span><span><b>M</b>米芝蓮</span><span>灰色＝已收錄時間顯示休息</span></div>}
  </section>
  <nav className="bottom-nav" aria-label="主要頁面">{[['map','map','地圖'],['list','list','清單'],['route','route','行程'],['favorites','heart','收藏']].map(([v,icon,label])=><button key={v} aria-current={view===v?'page':undefined} className={view===v?'active':''} onClick={()=>switchView(v)}><Icon name={v==='favorites'&&view===v?'saved':icon}/><span>{label}</span>{v==='favorites'&&favorites.length>0&&<em>{favorites.length}</em>}</button>)}</nav>
  {selected&&<Dialog label={selected.name} onClose={()=>select(null)}><Photo key={selected.id} place={selected} large/><div className="detail-heading"><span className="eyebrow">{selected.district} · {selected.category}{selected.michelin?' · '+selected.michelin:''}</span><h2>{selected.name}</h2><p className="english">{selected.en}</p><span className={'status '+detailStatus.state}>{detailStatus.label}{detailStatus.next?' · '+detailStatus.next+' 再開':''}</span></div><p className="description">{selected.description}</p><div className="detail-grid"><div><span className="label">不可錯過</span><strong>{selected.signature}</strong></div><div><span className="label">人均規劃預算</span><strong>{budgetLabel(selected)}</strong><small>{selected.priceNote||'估算，非即時餐牌報價'}</small></div></div><div className="detail-fact"><span className="label">到場辨認</span><p>{selected.arrival}</p><strong>{selected.address}</strong></div><div className="detail-fact"><span className="label">營業／開放時間 · 香港時間</span><p>{selected.hours}</p><small>按刊載資料推算，非即時店況；假期及臨時安排請再確認。</small></div><div className="detail-fact"><span className="label">訂位及到訪</span><p>{selected.booking}</p>{selected.website&&<a href={selected.website} target="_blank" rel="noreferrer">官方網站 ↗</a>}{selected.phone&&<a href={'tel:'+selected.phone}>致電 {selected.phone}</a>}</div><details className="source-details"><summary>收錄理由與核對紀錄</summary><p>{selected.selectionReason}</p>{selected.rating&&<p>Google 評分轉載快照：{selected.rating}／5 · {selected.reviewCount.toLocaleString()} 則。查閱日 {selected.checkedAt}，非 Google 即時核實。</p>}<p>{selected.reviewAudit}</p><p>座標：{selected.geoNote}</p>{selected.sources.map((s,i)=><a key={s.url} href={s.url} target="_blank" rel="noreferrer">{i+1}. {s.label} ↗</a>)}</details><div className="detail-actions"><button onClick={()=>toggle('favorites',favorites,setFavorites,selected.id)}><Icon name={favorites.includes(selected.id)?'saved':'heart'}/>{favorites.includes(selected.id)?'已收藏':'收藏'}</button><button onClick={()=>toggle('visited',visited,setVisited,selected.id)}><Icon name="check"/>{visited.includes(selected.id)?'已去過':'標記去過'}</button><button onClick={()=>share(selected)}>分享 ↗</button></div><button className="route-add" onClick={()=>addRoute(selected)}><Icon name="plus"/>加入口袋行程</button><div className="navigation-links"><a href={mapsUrl(selected)} target="_blank" rel="noreferrer">Google Maps ↗</a><a href={mapsUrl(selected,'apple')} target="_blank" rel="noreferrer">Apple Maps ↗</a></div></Dialog>}
  {showFilters&&<Dialog label="距離及預算" onClose={()=>setShowFilters(false)}><span className="eyebrow">A LITTLE CLOSER</span><h2>揀得再貼心一點。</h2><label className="form-field">人均預算上限<select value={budget} onChange={e=>setBudget(Number(e.target.value))}>{[[0,'不限'],[60,'HK$60'],[100,'HK$100'],[200,'HK$200'],[400,'HK$400'],[800,'HK$800']].map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label><label className="check-field"><input type="checkbox" checked={nearby} onChange={e=>{setNearby(e.target.checked);if(e.target.checked&&!location)locate()}}/>只看附近 3 km</label><p className="muted">按直線距離，未計山坡、跨海及步行路線。預算以估算上限篩選；未知預算不納入。</p><button className="primary" onClick={()=>setShowFilters(false)}>顯示 {filtered.length} 個結果</button><button className="text-button" onClick={()=>{setBudget(0);setNearby(false)}}>重設距離及預算</button></Dialog>}
  {install&&<Dialog label="加入主畫面" onClose={()=>setInstall(false)}><span className="brand-mark">港</span><h2>把香港，放進口袋。</h2><ol><li>使用 iPhone Safari 開啟這個網址。</li><li>按「分享」，選「加入主畫面」。</li><li>如有「以 Web App 開啟」選項，請開啟。</li></ol><p>收藏保存在這部裝置。載入過的地點資料可離線查看；新地圖區域、定位和外部網站仍可能需要網絡。</p></Dialog>}
  {about&&<Dialog label="收錄準則" onClose={()=>setAbout(false)}><span className="eyebrow">CURATED, NOT CROWDSOURCED</span><h2>好去處，也要有依據。</h2><p>首版逐間核對，並非全港餐廳普查。按菜式篩選；米芝蓮只作額外識別。</p><ul><li>米芝蓮或具可靠獨立推薦依據的代表性老店：Google 至少 4.0；排除純素食餐廳。</li><li>一般餐廳：4.2 分及至少 300 則；Cafe／甜品：4.3 分及至少 150 則。OpenRice 用作食評內容及好／一般／差評交叉核對，不換算成星數。</li><li>門面照片、現址及營業時間分開核對。時間未知不會誤判打烊。</li><li>優惠換好評、要求五星或其他明確刷分證據：排除。只有 PR／贊助推介支持：不收錄。公開抽查未發現不等於保證不存在，平台轉載亦可能過時。</li><li>人均是規劃估算，另留意加一服務費；景點的館內、園區與商戶時間可能不同。</li></ul><p>資料查閱：2026-09-14。逐店來源在詳情卡；香港收藏與峴港版分開。</p><p>© OpenStreetMap contributors。實景照片來源及授權各自列明。</p></Dialog>}
  {needRefresh&&<div className="update-toast" role="status">新版已就緒<button onClick={()=>updateServiceWorker(true)}>套用更新</button><button aria-label="稍後更新" onClick={()=>setNeedRefresh(false)}>×</button></div>}
  {notice&&<div className="toast" role="status">{notice}</div>}
 </main>
}
